### ISSUE TITLE
last.fm support

### ISSUE THREAD

**Issue by Owlz** [alexolivero/Obscurify#4]
Hi Alex, I was wondering if it could be possible to implement a login through last.fm as I don't use spotify and  the former is what has been tracking my music listening for the last 6~ years

I'm willing to take a look at the code and put together a pull request in the next few days if the idea is accepted (be aware: I have never done a pull request before, it might take some time and patience on your end)

**Comment by alexolivero** [comment]
Hey Luca,

I love the idea, you are more than welcome to submit a PR. I'll be happy to
help you as well. However, I'm not exactly sure what features you're
suggesting? I would love to see some more details, so we can decide how to
get it working.

Thanks,
Alex

**Comment by Owlz** [comment]
The idea is to make obscurify work with last.fm

To implement such feature there will be needed:
- A new way to login to obscurifymusic through the use of the last.fm API (this might not be needed as the important infos are public on last.fm)
- A way to generate the same report with the last.fm api

All the API calls are listed [here](https://www.last.fm/api/), i'm not sure which one will be needed

**Comment by alexolivero** [comment]
Hey Luca,

This is some good info. The main challenge I see right now is that Last.fm
doesn't do "popularity" at all, so we would need to correlate the Last.fm
tracks/artists with Spotify to get that data. For example: we have your top
50 songs according to last fm. In order to get the popularity + moods
(happiness, danceability, etc) we would have to get the Spotify track IDs
for those last fm tracks. That might require 50 Search api calls to Spotify
to get those tracks.

Did you want to put together a proof of concept, and we can take a look at
merging it into the existing codebase?

Thanks,
Alex

**Comment by Owlz** [comment]
I see the impracticality of such implementation and, unfortunately, I suppose it will render this whole idea useless.

I will still try to build a demo in the next few months and I'll post the result if it is enough robust and reliable.

Thanks again for the clarification, feel free to close this issue.

**Comment by alexolivero** [comment]
Go for it, let me know how it goes! Even if it's not the most elegantly designed I would love to see it.
